apiVersion: v1
kind: Service
metadata:
  name: {{ include "akstest.fullname" . }}
  labels:
    {{- include "akstest.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "akstest.selectorLabels" . | nindent 4 }}
